In [ ]:
#Task1

import numpy as np
N = int(input("Enter the values:"))

arr = np.zeros(N, dtype=int)
for i in range(0,N):
  value = int(input())
  arr[i]=value

print("Original Array:",arr)

arr1 = np.zeros(N+1,dtype=int)
for i in range(0,N):
  arr1[i]=arr[i]

new_value = int(input("Enter the new value:"))
arr1[len(arr1)-1]=new_value

print("Resized Array:",arr1)

Enter the values:3
7
8
9
Original Array: [7 8 9]
Enter the new value:90
Resized Array: [ 7  8  9 90]


In [ ]:
#Task2

from ast import arg
import numpy as np
N = int(input("Enter the values:"))

arr = np.zeros(N, dtype=int)
for i in range(0,N):
  value = int(input())
  arr[i]=value

print("Original Array:",arr)

for i in range(0,len(arr)):
  if arr[i]==0:
    continue
  if arr[i]>0:
    arr[i]=1
  else:
    arr[i]=0

print("After modifying:",arr)

Enter the values:3
5
7
9
Original Array: [5 7 9]
After modifying: [1 1 1]


In [ ]:
#TAsk3

import numpy as np

def reverseArray(arr):
    length = len(arr)
    for i in range(length // 2):
        temp = arr[i]
        arr[i] = arr[length-i-1]
        arr[length-i-1] = temp
    return arr

arr1 = np.array([10, 12, 20, 5, 7])
arr1 = reverseArray(arr1)

print(arr1)

[ 7  5 20 12 10]


In [ ]:
import numpy as np

def reverseArray(arr):
    length = len(arr)
    for i in range(length // 2):
        temp = arr[i]
        arr[i] = arr[length-i-1]
        arr[length-i-1] = temp
    return arr

arr2 = np.array([4, 2, 6, 5])
arr2 = reverseArray(arr2)

print(arr2)


[5 6 2 4]


In [ ]:
#Task4

def printPairs(arr,val):
  flag = False
  for i in range(arr.size):
    for j in range(i+1,arr.size):
      if arr[i] + arr[j] == val:
        flag = True
        print(f"{arr[i]}, {arr[j]}")
  if flag == False:
    print("No Pair Found")
arr1 = np.array([7,8,10,5,3,4,2])
printPairs(arr1, 15)


7, 8
10, 5


In [ ]:
#task5

import numpy as np

def product(vec1, vec2):
    dot_product = 0
    for i in range(len(vec1)):
        dot_product += vec1[i] * vec2[i]
    print("Dot Product:", dot_product)

    if dot_product % 2 == 0:
        for i in range(len(vec1)):
            if i % 2 == 0:
                temp = vec1[i]
                vec1[i] = vec2[i]
                vec2[i] = temp
    else:
        for i in range(len(vec1)):
            if i % 2 != 0:
                temp = vec1[i]
                vec1[i] = vec2[i]
                vec2[i] = temp
    print(f"After Swapping:\n{vec1}\n{vec2}")

vec1 = np.array([1,2,3,7])
vec2 = np.array([4,5,6,9])

product(vec1, vec2)

Dot Product: 95
After Swapping:
[1 5 3 9]
[4 2 6 7]


In [3]:
#Task 6
import numpy as np
N = int(input("Sir, please enter the length: "))
array = np.zeros(N,dtype = int)

for i in range(array.size):
  array[i] = int(input("Sir, please enter the values: "))
print("Original Array:",array)
for j in range(array.size):
  for k in range(array.size-j-1):
    if array[k] > array[k+1]:
      temp = array[k]
      array[k] = array[k+1]
      array[k+1] = temp

print("Sorted Array:",array)

Sir, please enter the length: 6
Sir, please enter the values: 3
Sir, please enter the values: 6
Sir, please enter the values: 1
Sir, please enter the values: 2
Sir, please enter the values: 8
Sir, please enter the values: 5
Original Array: [3 6 1 2 8 5]
Sorted Array: [1 2 3 5 6 8]


In [ ]:
#task7

import numpy as np

def flatten(arr):
    return arr.flatten()

arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = flatten(arr1)
print(arr2)



[1 2 3 3 4 5]


In [ ]:
import numpy as np

def flatten(arr):
    return arr.flatten()
arr3 = np.array( [ [1, 4], [5, 6],[8, 9] ] )
arr4 = flatten(arr3)
print(arr4)

[1 4 5 6 8 9]


In [2]:
#task8

import numpy as np

def check_identity_matrix(matrix):
    rows, cols = matrix.shape
    if rows != cols:
        return "Not a square matrix"
    for i in range(rows):
        for j in range(cols):
            if i == j and matrix[i][j] != 1:
                return "Not an Identity matrix"
            elif i != j and matrix[i][j] != 0:
                return "Not an Identity matrix"
    return "Identity matrix"

A = np.array([ [1,  0,  0,  1],[0,  1,  0,  0],[1,  0,  1,  0],[0,  1,  0,  1] ])


result = check_identity_matrix(A)
print(result)

Not an Identity matrix


In [1]:
#task9

import numpy as np

def diagonal(matrix):
    n = len(matrix)
    primary = sum(matrix[i][i] for i in range(n))
    secondary = sum(matrix[i][n - i - 1] for i in range(n))
    return abs(primary - secondary)

A = np.array([[1, 5, 12, 1],[2, -4, 6, 7],[3, 8, 5, 9],[3, 5, 23, -6]])

result = diagonal(A)
print(result)

22


In [ ]:
#task10

#10.1
import numpy as np

A = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

AT = np.transpose(A)

print(AT)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
#10.2

import numpy as np

A = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

AT = np.transpose(A)
rows, cols = AT.shape

arr = np.zeros((rows, rows),dtype=int)

for i in range(rows):
    for j in range(rows):
        for k in range(cols):
            arr[i][j] += AT[i][k] * A[k][j]

print(arr)

[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]


In [27]:
#Task11
import numpy as np

A = np.array([[6,3],[1,5]])
row = A.shape[0]
col = A.shape[1]
subs = abs(row - col)
remain = subs % row

sum = 0
for i in range(0, col):
  sum += A[remain][i]
avg = round(sum/col,2)
final_array = (A*float(avg))
print(final_array)

[[27.  13.5]
 [ 4.5 22.5]]


In [26]:
#Task11

import numpy as np

def process_array(A):
    M, N = A.shape
    new_array = np.zeros_like(A,dtype= float)

    absolute_difference = abs(M - N)
    remainder = absolute_difference % M
    print(remainder)
    average_row = np.mean(A[remainder])
    print(average_row)
    #for i in range(M):
      #for j in range(N):
    new_array= A* average_row

    return new_array

# Sample Given Array
A = np.array([[6,3],[1,5]])

# Process the array
result = process_array(A)

# Display the new array rounded to 2 decimal places
print(np.round(result))


0
4.5
[[27. 14.]
 [ 4. 22.]]


In [7]:
#Task11

import numpy as np

def calculate_and_multiply(A):
    # Get the shape of the input array
    rows, cols = A.shape

    # Calculate the absolute value difference between row and column numbers
    abs_diff = abs(rows - cols)

    # Calculate the remainder when dividing the absolute difference by the number of rows
    remainder = abs_diff % rows

    # Select the row based on the remainder
    selected_row = A[remainder]

    # Calculate the average of the selected row
    average_value = np.mean(selected_row)

    # Multiply each element of the array by the average value
    result = A * average_value

    return result

# Sample input array
A = np.array([[4, 1, 2], [9, 3, 7]])

# Calculate and print the result
output = calculate_and_multiply(A)
print(output)


[[25.33333333  6.33333333 12.66666667]
 [57.         19.         44.33333333]]
