In [1]:
# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

/usr/local/lib/python3.10/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


In [ ]:
#You must run this cell to print matrix and for the driver code to work
def print_matrix(m):
  row,col = m.shape
  for i in range(row):
    c = 1
    print('|', end='')
    for j in range(col):
      c += 1
      if(len(str(m[i][j])) == 1):
        print(' ',m[i][j], end = '  |')
        c += 6
      else:
        print(' ',m[i][j], end = ' |')
        c += 6
    print()
    print('-'*(c-col))



In [ ]:
array1 = np.array([[0, 4, 1], [7, 2, 5], [3, 6, 0]])
array2 = np.array([[3, 6, 0], [5, 2, 7], [0, 4, 1]])


In [ ]:
m = np.array([[0, 4, 1], [7, 2, 5], [3, 6, 0]])

row,col = m.shape

#new = np.zeros((row,col), dtype=int)

for i in range(row):
  for j in range(col//2):
    m[i] [j] ,m[i][col-1-j] = m[i][col-1-j] , m[i][j]
print(m)



[[1 4 0]
 [5 2 7]
 [0 6 3]]


In [ ]:
m = np.array([[0, 4, 1], [7, 2, 5], [3, 6, 0]])

row,col = m.shape

#new = np.zeros((row,col), dtype=int)

for i in range(row//2):
  for j in range(col):
    m[i] [j] ,m[row-1-i][j] = m[row-1-i][j] , m[i][j]
print(m)

for i in range(row):
  for j in range(col//2):
    m[i] [j] ,m[i][col-1-j] = m[i][col-1-j] , m[i][j]
print(m)


[[3 6 0]
 [7 2 5]
 [0 4 1]]
[[0 6 3]
 [5 2 7]
 [1 4 0]]


In [ ]:
array1 = np.array([[0, 4, 1], [7, 2, 5], [3, 6, 0]])
array2 = np.array([[3, 6, 0], [5, 2, 7], [0, 4, 1]])


row,col = array1.shape

n1=np.zeros(col, dtype=int)
n2=np.zeros(col, dtype=int)

for i in range(row):
  for j in range(col):
    if i+j == row-1:
      n1[i]=m[i][j]

for i in range(row):
  for j in range(col):
    if i==j:
      n2[i]=m[i][j]

for k in range (len(n2)):
  for l in range((len(n2)-1),0,-1):
    s=n2[k]
    n2[k]=n2[l]
    n2[l]= s

print(n1)
print(n2)

#if n1 == n2:
  #print("YES")


[1 2 3]
[2 0 0]


In [ ]:
array1 = np.array([[0, 4, 1], [7, 2, 5], [3, 6, 0]])
array2 = np.array([[3, 6, 0], [5, 2, 7], [0, 4, 1]])


row,col = array1.shape


for i in range(row):
  for j in range(col):

    for k in range(row-1,0,-1):
      for l in range(col-1,0,-1):

        if i+j== row-1:
          if k==l:
            if array1[i][j] == array2[k][l]:
              a="YES"
            else:
              a="No"
print(a)

No


In [ ]:
array1 = np.array([[0, 4, 1], [7, 2, 5], [3, 6, 0]])
array2 = np.array([[3, 6, 0], [5, 2, 7], [0, 4, 1]])


row,col = array1.shape

n1=np.zeros(row, dtype=int)

n2=np.zeros(row, dtype=int)

for i in range(row):
  for j in range(col):
    if i+j == row-1:
      n1[i]=array1[i][j]

for k in range(row):
  for l in range(col):
    if k==l:
      n2[k]=array2[k][l]

for m in range(len(n2)//2):
  for n in range((len(n2)-1),len(n2)//2,-1):
    s= n2[m]
    n2[m]=n2[n]
    n2[n]=s

for idx in n1:
  for idx2 in n2:
    if idx == idx2:
      a="YES"
    else:
      a="NO"

print(a)


YES
[1 2 3]
[1 2 3]


In [ ]:
array1 = np.array([[0, 9, 9, 1], [9, 0, 2, 9], [9, 3, 0, 9], [4, 9, 9, 0]])
array2 = np.array([[4, 9, 9, 0], [9, 0, 3, 9], [9, 0, 2, 9], [0, 9, 5, 1]])



row,col = array1.shape

n1=np.zeros(row, dtype=int)

n2=np.zeros(row, dtype=int)

for i in range(row):
  for j in range(col):
    if i+j == row-1:
      n1[i]=array1[i][j]

for k in range(row):
  for l in range(col):
    if k==l:
      n2[k]=array2[k][l]

for m in range(len(n2)//2):
  for n in range((len(n2)-1),len(n2)//2,-1):
    s= n2[m]
    n2[m]=n2[n]
    n2[n]=s

for idx in n1:
  for idx2 in n2:
    if idx == idx2:
      a="YES"
    else:
      a="NO"

print(a)
print(n1)
print(n2)


NO
[1 2 3 4]
[1 4 2 0]


In [ ]:
def check_Diagonal(matrix1, matrix2):
  #TO DO
  row,col = matrix1.shape

  n1=np.zeros(row, dtype=int)

  n2=np.zeros(row, dtype=int)

  for i in range(row):
    for j in range(col):
      if i+j == row-1:
        n1[i]=array1[i][j]

  for k in range(row):
    for l in range(col):
      if k==l:
        n2[k]=array2[k][l]

  for m in range(len(n2)//2):
    for n in range((len(n2)-1),len(n2)//2,-1):
      s= n2[m]
      n2[m]=n2[n]
      n2[n]=s

  for idx in n1:
    for idx2 in n2:
      if idx == idx2:
        a="YES"
      else:
        a="NO"

  print(a)


array1 = np.array([[0, 4, 1], [7, 2, 5], [3, 6, 0]])
array2 = np.array([[3, 6, 0], [5, 2, 7], [0, 4, 1]])

check_Diagonal(array1, array2) #This should print YES

print(".............")

array1 = np.array([[0, 9, 9, 1], [9, 0, 2, 9], [9, 3, 0, 9], [4, 9, 9, 0]])
array2 = np.array([[4, 9, 9, 0], [9, 0, 3, 9], [9, 0, 2, 9], [0, 9, 5, 1]])

check_Diagonal (array1, array2) #This should print NO

YES
.............
NO


Task 2: Row Rotation Policy of BRACU Classroom

In [ ]:
Task 3: Matrix Manipulation

**Task 3: Matrix Manipulation**

In [ ]:
def reverse_Matrix(matrix):
  #TO DO
  row,col = matrix.shape

  for i in range(row//2):
    for j in range(col):
      matrix[i] [j] ,matrix[row-1-i][j] = matrix[row-1-i][j] , matrix[i][j]

  for i in range(row):
    for j in range(col//2):
      matrix[i] [j] ,matrix[i][col-1-j] = matrix[i][col-1-j] , matrix[i][j]

  return matrix


matrix = np.array([
[14,  8,  0,  4],
[9,  8,  13,  13],
[9,  3,  1,  4],
[2,  10,  13,  6]
])
print(matrix)
print('################')
print()
reversed_matrix = reverse_Matrix(matrix)
print (reversed_matrix)

#This should print
#|  6  |  13 |  10 |  2  |
#-------------------------
#|  4  |  1  |  3  |  9  |
#-------------------------
#|  13  |  13  |  8 |  9 |
#-------------------------
#|  4 |  0  |  8  |  14  |
#-------------------------


[[14  8  0  4]
 [ 9  8 13 13]
 [ 9  3  1  4]
 [ 2 10 13  6]]
################

[[ 6 13 10  2]
 [ 4  1  3  9]
 [13 13  8  9]
 [ 4  0  8 14]]


In [ ]:
def play_game(arena):
  #TO DO
  row,col= arena.shape

  count=0

  for i in range(row):
    for j in range(col):
      if arena[i] [j]!=0 and arena[i][j]% 50== 0:

       if i-1>=0:
        if arena[i-1][j]==2:
          count+=1

        if i +1 <row-1:
          if arena [i+1][j] ==2:
            count+=1

        if j+1 <= col-1:
          if arena[i][j+1] ==2:
            count+=1

        if j-1>=0:
          if arena[i][j-1]==2:
            count+=1

  points= count * 2

  if points < 10:
    print(f"Points Gained: {points}. Your Team is out")
  else:
    print(f"Points Gained: {points}. Your team has survived the game.")


arena=np.array([[0,2,2,0],
                [50,1,2,0],
                [2,2,2,0],
                [1,100,2,0]
                ])
print(arena)
play_game(arena)
#This should print
#Points Gained: 6. Your team is out.

print(".....................")
arena=np.array([[0,2,2,0,2],
                [1,50,2,1,100],
                [2,2,2,0,2],
                [0,200,2,0,0]
                ])
print(arena)
play_game(arena)
#This should print
#Points Gained: 14. Your team has survived the game.

[[  0   2   2   0]
 [ 50   1   2   0]
 [  2   2   2   0]
 [  1 100   2   0]]
Points Gained: 6. Your Team is out
.....................
[[  0   2   2   0   2]
 [  1  50   2   1 100]
 [  2   2   2   0   2]
 [  0 200   2   0   0]]
Points Gained: 14. Your team has survived the game.


In [ ]:
def play_game(arena):
  #TO DO
  row,col= arena.shape

  point=0

  for i in range(row):
    for j in range(col):
      if arena [i][j] !=0 and arena[i][j]% 50== 0:

        if i == 0:

          if j ==0:

            if arena[i][j+1] == 2:
              point+=2
            if arena [i+1] [j]==2:
              point+=2

          elif j == row-1:

            if arena[i][j-1] ==2:
              point+=2
            if arena [i+1][j]==2:
              point+=2
          else:
            if arena[i][j+1] == 2:
              point+=2
            if arena[i][j-1] == 2:
              point+=2
            if arena[i+1][j] == 2:
              point+=2

        elif i == row-1:

          if j ==0:

            if arena[i][j+1] ==2:
              point+=2
            if arena [i-1][j]==2:
              point+=2

          elif j == col-1:

            if arena[i][j-1] ==2:
              point+=2
            if arena [i-1][j]==2:
              point+=2
          else:
            if arena[i][j+1] == 2:
              point+=2
            if arena[i][j-1] == 2:
              point+=2
            if arena[i-1][j] == 2:
              point+=2

        elif j ==0 and (1<=i<3):


          if arena[i][j+1] == 2:
            point+=2
          if arena[i+1][j] == 2:
            point+=2
          if arena[i-1][j] == 2:
            point+=2

        elif j == col-1 and (1<=i<3):

          if arena[i][j-1] == 2:
            point+=2
          if arena[i-1][j] == 2:
            point+=2
          if arena[i+1][j] == 2:
            point+=2


        else:

          if arena[i][j+1] == 2:
            point+=2
          if arena[i][j-1] == 2:
            point+=2
          if arena[i+1][j] == 2:
            point+=2
          if arena[i-1][j] ==2:
            point+=2



  if point < 10:
    print(f"Points Gained: {point}. Your Team is out")
  else:
    print(f"Points Gained: {point}. Your team has survived the game.")



arena=np.array([[0,2,2,0],
                [50,1,2,0],
                [2,2,2,0],
                [1,100,2,0]
                ])
print(arena)
play_game(arena)
#This should print
#Points Gained: 6. Your team is out.

print(".....................")
arena=np.array([[0,2,2,0,2],
                [1,50,2,1,100],
                [2,2,2,0,2],
                [0,200,2,0,0]
                ])
print(arena)
play_game(arena)
#This should print
#Points Gained: 14. Your team has survived the game.

[[  0   2   2   0]
 [ 50   1   2   0]
 [  2   2   2   0]
 [  1 100   2   0]]
Points Gained: 16. Your team has survived the game.
.....................
[[  0   2   2   0   2]
 [  1  50   2   1 100]
 [  2   2   2   0   2]
 [  0 200   2   0   0]]
Points Gained: 28. Your team has survived the game.


In [ ]:
def calculate_points(matrix):
    rows = len(matrix)
    cols = len(matrix[0])
    points = 0

    for i in range(rows):
        for j in range(cols):
            if matrix[i][j] %50== 0:  # Only consider positions with values > 0
                # Check neighboring cells
                # Up
                if i > 0 and matrix[i - 1][j] == 2:
                    points += 1
                # Down
                if i < rows - 1 and matrix[i + 1][j] == 2:
                    points += 1
                # Left
                if j > 0 and matrix[i][j - 1] == 2:
                    points += 1
                # Right
                if j < cols - 1 and matrix[i][j + 1] == 2:
                    points += 1

    return points

def game_result(matrix):
    points = calculate_points(matrix)
    if points >= 10:
        return f"Points Gained: {points}. Your team has survived the game."
    else:
        return f"Points Gained: {points}. Your team is out."

# Sample Input 1
matrix1 = [
    [0, 2, 2, 0],
    [50, 1, 2, 0],
    [2, 2, 2, 0],
    [1, 100, 2, 0]
]

# Sample Input 2
matrix2 = [
    [0, 2, 2, 0, 2],
    [1, 50, 2, 1, 100],
    [2, 2, 2, 0, 2],
    [0, 200, 2, 0, 0]
]

print(game_result(matrix1))
print(game_result(matrix2))


Points Gained: 8. Your team is out.
Points Gained: 15. Your team has survived the game.


In [ ]:
#Task3

def row_rotation(exam_week, seat_status):
  #To Do
  row,col=seat_status.shape
  m=np.array([["A","B","C","D","E"]])
  x,y=m.shape


  for i in range(row-1):
    for j in range(col):
      for k in range(x):
        for l in range(y):
          m[x][y]= seat_status[i][j]

  print(m)




seat_status = np.array([[ 'A' , 'B' , 'C' , 'D' , 'E'],
                  ['F' , 'G' , 'H' , 'I' , 'J'],
                  ['K' , 'L' , 'M' , 'N' , 'O'],
                  ['P' , 'Q' , 'R' , 'S' , 'T'],
                  ['U' , 'V' , 'W' , 'X' , 'Y'],
                  ['Z' , 'AA' , 'BB' , 'CC' , 'DD']])
exam_week=3
print(seat_status)
print()
row_number=row_rotation(exam_week, seat_status) #This should print modified seat status after rotation
print(f'Your friend AA will be on row {row_number}') #This should print Your friend AA will be on row 2

[['A' 'B' 'C' 'D' 'E']
 ['F' 'G' 'H' 'I' 'J']
 ['K' 'L' 'M' 'N' 'O']
 ['P' 'Q' 'R' 'S' 'T']
 ['U' 'V' 'W' 'X' 'Y']
 ['Z' 'AA' 'BB' 'CC' 'DD']]



IndexError: index 1 is out of bounds for axis 0 with size 1

In [ ]:
def row_rotation(exam_week, seat_status):
  #To Do
  row, col = seat_status.shape

  for n in range(exam_week-1):
    temp = [" "]*col
    c = 0
    for i in range(col):
      temp[c] = seat_status[row-1][i]
      c += 1
    # print(temp)
    for i in range(row-1, 0, -1):
      for j in range(col):

        seat_status[i][j] = seat_status[i-1][j]
    for m in range(col):
        seat_status[0][m] = temp[m]
  print(seat_status)

  found = 0
  for i in range(row):
    for j in range(col):
      if seat_status[i][j] == 'AA':
        found = i + i
        break

  return found

seat_status = np.array([[ 'A' , 'B' , 'C' , 'D' , 'E'],
                  ['F' , 'G' , 'H' , 'I' , 'J'],
                  ['K' , 'L' , 'M' , 'N' , 'O'],
                  ['P' , 'Q' , 'R' , 'S' , 'T'],
                  ['U' , 'V' , 'W' , 'X' , 'Y'],
                  ['Z' , 'AA' , 'BB' , 'CC' , 'DD']])
exam_week=3
print(seat_status)
print()
row_number=row_rotation(exam_week, seat_status) #This should print modified seat status after rotation
print(f'Your friend AA will be on row {row_number}') #This should print Your friend AA will be on row 2

[['A' 'B' 'C' 'D' 'E']
 ['F' 'G' 'H' 'I' 'J']
 ['K' 'L' 'M' 'N' 'O']
 ['P' 'Q' 'R' 'S' 'T']
 ['U' 'V' 'W' 'X' 'Y']
 ['Z' 'AA' 'BB' 'CC' 'DD']]

[['U' 'V' 'W' 'X' 'Y']
 ['Z' 'AA' 'BB' 'CC' 'DD']
 ['A' 'B' 'C' 'D' 'E']
 ['F' 'G' 'H' 'I' 'J']
 ['K' 'L' 'M' 'N' 'O']
 ['P' 'Q' 'R' 'S' 'T']]
Your friend AA will be on row 2


In [ ]:
def show_knight_move(knight):
  #To Do
    x,y= knight
    chess= np.zeros((8,8), dtype=int)
    print(chess)
    for i in range(row):
      for j in range(col):







 knight=(3,4)
chess_board = show_knight_move(knight)
print_matrix(chess_board)
#This Should print
#| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 3 | 0 | 3 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 3 | 0 | 0 | 0 | 3 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 0 | 66 | 0 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 3 | 0 | 0 | 0 | 3 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 3 | 0 | 3 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 15)

In [ ]:
def show_knight_move(knight):
  #To Do
  x,y= knight
  chess= np.zeros((8,8), dtype=int)
  #print(chess)

  for i in range(8):
    for j in range(8):
      if i ==x and j ==y:
        chess[i][j]= 66
        if



  print(chess)




knight = (3,4)
chess_board = show_knight_move(knight)
print(chess_board)
#This Should print
#| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 3 | 0 | 3 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 3 | 0 | 0 | 0 | 3 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 0 | 66 | 0 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 3 | 0 | 0 | 0 | 3 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 3 | 0 | 3 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
#-----------------------------------------

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0 66  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
None


In [ ]:

import numpy as np

def compress_matrix(mat):
    #TO DO
    row,col= mat.shape

    m=row-2
    n=col-2

    one_D= np.zeros(row, dtype=int)
    comp= np.zeros((m,n), dtype=int)

    x=0
    for i in range(0,row,2):
      for j in range(0,col,2):
        sum = mat[i][j] + mat [i][j+1] + mat[i+1][j]+ mat[i+1][j+1]
        one_D[x]=sum
        x+=1

    p=0
    for k in range(m):
        for l in range(n):
          comp[k][l] = one_D[p]
          p+=1


    return comp





matrix=np.array([[1,2,3,4],
                 [5,6,7,8],
                 [1,3,5,2],
                 [-2,0,6,-3]
                 ])
print (matrix)
print('################')
print()
returned_array=compress_matrix(matrix)
print (returned_array)
#This should print
#|  14  |  22 |
#--------------
#|  2  |  10  |
#--------------

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 1  3  5  2]
 [-2  0  6 -3]]
################

[[14 22]
 [ 2 10]]


In [6]:
#

import numpy as np

m= np.array([2,4,3,2,3])

temp= m[0]

for i in range(1,len(m)):
  if m[i] != temp:
    temp=m[0]
  else:
    temp=m[i]
print(temp)

2


In [12]:
import numpy as np

m= np.array([2,4,3,2,3])
n= [0]*len(m)


j=0
for i in range(len(m)):
  for j in range(i+1,len(m)):
    if m[i] == m[j]:
      c+=1
    elif m[i] != m[j]:
      print(m[i])



2
2
2
4
4
4
3
2
