In [6]:
import numpy as np

In [12]:
m= np.array ([[15,13,7],[19,5,8],[23,19,21]])

#m = np.array([[0, 4, 1], [7, 2, 5], [3, 6, 0]])


row,col=m.shape

n=np.zeros(row, dtype=int)
print(n)

c=0
max=0

for i in range(row):
  for j in range(col):

    if m[i][j] > m[i][j+1]:
      max=m[i][j]
    else:
      max= m[i][j+1]
  n[c]=max
  c+=1
print(n)

v=0
for j in range(col):
  for i in range(row):
    if m[i][j] < n[c]:
      print(m[i][j])
    else:
      c+=1


[0 0 0]


IndexError: index 3 is out of bounds for axis 0 with size 3

In [ ]:
m = np.array([[0, 4, 1], [7, 2, 5], [3, 6, 0]])

row,col = m.shape

#new = np.zeros((row,col), dtype=int)

for i in range(row):
  for j in range(col//2):
    m[i] [j] ,m[i][col-1-j] = m[i][col-1-j] , m[i][j]
print(m)



[[1 4 0]
 [5 2 7]
 [0 6 3]]


In [ ]:
m = np.array([[0, 4, 1], [7, 2, 5], [3, 6, 0]])

row,col = m.shape

#new = np.zeros((row,col), dtype=int)

for i in range(row):
  for j in range(col//2):
    m[i] [j] ,m[i][col-1-j] = m[i][col-1-j] , m[i][j]
print(m)



[[1 4 0]
 [5 2 7]
 [0 6 3]]
